"use client";
import Link from "next/link";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { RequireAuth } from "../../features/auth/require-auth";
import { useAuth } from "../../features/auth/use-auth";
import { canManageNotificationRules } from "../../features/auth/rbac";
import { apiClient } from "../../lib/api-client";
import { useNotificationRuleMutations, useNotificationRules, useNotifications } from "../../features/notifications/hooks";
import type { NotificationEventType, NotificationRule, NotificationStatus } from "../../features/notifications/types";

const EVENTS: NotificationEventType[] = ["APPROVAL_REQUESTED", "APPROVAL_APPROVED", "APPROVAL_REJECTED", "APPROVAL_EXPIRED", "EXECUTION_COMPLETED", "EXECUTION_FAILED", "EVENT_TRIGGER_FAILED", "EVENT_CHAIN_DEPTH_EXCEEDED"];
const TEMPLATES: Record<NotificationEventType, string> = { APPROVAL_REQUESTED: "approval.requested", APPROVAL_APPROVED: "approval.approved", APPROVAL_REJECTED: "approval.rejected", APPROVAL_EXPIRED: "approval.expired", EXECUTION_COMPLETED: "workflow.completed", EXECUTION_FAILED: "workflow.failed", EVENT_TRIGGER_FAILED: "event-trigger.failed", EVENT_CHAIN_DEPTH_EXCEEDED: "event-chain.depth-exceeded" };
const LABELS: Partial<Record<NotificationEventType, string>> = { EXECUTION_COMPLETED: "WORKFLOW_COMPLETED", EXECUTION_FAILED: "WORKFLOW_FAILED" };

export default function NotificationsPage() {
  const [tab, setTab] = useState<"rules" | "deliveries">("rules"); const { organizations, activeOrganizationId } = useAuth(); const role = organizations.find((item) => item.id === activeOrganizationId)?.role; const canManage = canManageNotificationRules(role);
  return <RequireAuth><main className="content stack"><h1>Notifications</h1><div><button onClick={() => setTab("rules")} disabled={tab === "rules"}>Rules</button> <button onClick={() => setTab("deliveries")} disabled={tab === "deliveries"}>Deliveries</button></div>{tab === "rules" ? <Rules canManage={canManage} /> : <Deliveries />}</main></RequireAuth>;
}

function Rules({ canManage }: { canManage: boolean }) {
  const query = useNotificationRules(); const mutations = useNotificationRuleMutations(); const { activeOrganizationId } = useAuth(); const [editing, setEditing] = useState<NotificationRule | null>(null); const [showForm, setShowForm] = useState(false);
  const connections = useQuery({ queryKey: ["connections", activeOrganizationId, "smtp-notifications"], queryFn: () => apiClient.get<Array<{ id: string; name: string; status: string }>>("/connections", { type: "SMTP", status: "ACTIVE" }), enabled: Boolean(activeOrganizationId && canManage) });
  return <section className="stack">{canManage && <button onClick={() => { setEditing(null); setShowForm(true); }}>Create rule</button>}{showForm && <RuleForm initial={editing} connections={connections.data ?? []} busy={mutations.create.isPending || mutations.update.isPending} onCancel={() => setShowForm(false)} onSave={(dto) => { const operation = editing ? mutations.update.mutateAsync({ id: editing.id, dto }) : mutations.create.mutateAsync(dto); void operation.then(() => { setShowForm(false); setEditing(null); }); }} />}{query.isLoading && <p>Loading rules...</p>}{query.error && <p role="alert">Could not load notification rules.</p>}<div className="panel"><table className="table"><thead><tr><th>Event</th><th>Channel</th><th>Recipient</th><th>Connection</th><th>Enabled</th>{canManage && <th>Actions</th>}</tr></thead><tbody>{query.data?.map((rule) => <tr key={rule.id}><td>{LABELS[rule.eventType] ?? rule.eventType}</td><td>{rule.channel}</td><td>{rule.recipientConfigJson.kind === "EMAILS" ? rule.recipientConfigJson.emails.join(", ") : `Roles: ${rule.recipientConfigJson.roles.join(", ")}`}</td><td>{rule.connection.name}</td><td>{rule.enabled ? "Yes" : "No"}</td>{canManage && <td><button onClick={() => { setEditing(rule); setShowForm(true); }}>Edit</button> <button onClick={() => { if (window.confirm("Delete this notification rule?")) mutations.remove.mutate(rule.id); }}>Delete</button></td>}</tr>)}</tbody></table></div></section>;
}

function RuleForm({ initial, connections, busy, onCancel, onSave }: { initial: NotificationRule | null; connections: Array<{ id: string; name: string }>; busy: boolean; onCancel: () => void; onSave: (dto: Record<string, unknown>) => void }) {
  const [eventType, setEventType] = useState<NotificationEventType>(initial?.eventType ?? "APPROVAL_REQUESTED"); const initialRecipients = initial?.recipientConfigJson; const [kind, setKind] = useState<"EMAILS" | "APPROVAL_ROLES">(initialRecipients?.kind ?? "EMAILS"); const [emails, setEmails] = useState(initialRecipients?.kind === "EMAILS" ? initialRecipients.emails.join(", ") : ""); const [roles, setRoles] = useState<string[]>(initialRecipients?.kind === "APPROVAL_ROLES" ? initialRecipients.roles : ["owner", "admin"]); const [connectionId, setConnectionId] = useState(initial?.connectionId ?? connections[0]?.id ?? ""); const [enabled, setEnabled] = useState(initial?.enabled ?? true); const approval = eventType.startsWith("APPROVAL_");
  return <form className="panel stack" onSubmit={(event) => { event.preventDefault(); onSave({ eventType, channel: "EMAIL", connectionId, enabled, templateKey: TEMPLATES[eventType], filters: initial?.filtersJson ?? {}, recipientConfig: kind === "EMAILS" ? { kind, emails: emails.split(",").map((value) => value.trim()).filter(Boolean) } : { kind, roles } }); }}><h2>{initial ? "Edit rule" : "Create rule"}</h2><label>Event type<select value={eventType} onChange={(event) => { const value = event.target.value as NotificationEventType; setEventType(value); if (!value.startsWith("APPROVAL_")) setKind("EMAILS"); }}>{EVENTS.map((value) => <option key={value} value={value}>{LABELS[value] ?? value}</option>)}</select></label><label>SMTP connection<select required value={connectionId} onChange={(event) => setConnectionId(event.target.value)}><option value="">Select connection</option>{connections.map((connection) => <option key={connection.id} value={connection.id}>{connection.name}</option>)}</select></label>{approval && <label>Recipient mode<select value={kind} onChange={(event) => setKind(event.target.value as any)}><option value="EMAILS">Explicit emails</option><option value="APPROVAL_ROLES">Authorized approval roles</option></select></label>}{kind === "EMAILS" ? <label>Recipient emails<input required value={emails} onChange={(event) => setEmails(event.target.value)} placeholder="ops@example.com, owner@example.com" /></label> : <fieldset><legend>Roles</legend>{["owner", "admin", "editor", "viewer"].map((role) => <label key={role}><input type="checkbox" checked={roles.includes(role)} onChange={(event) => setRoles(event.target.checked ? [...roles, role] : roles.filter((item) => item !== role))} /> {role}</label>)}</fieldset>}<label><input type="checkbox" checked={enabled} onChange={(event) => setEnabled(event.target.checked)} /> Enabled</label><div><button disabled={busy || !connectionId}>Save</button> <button type="button" onClick={onCancel}>Cancel</button></div></form>;
}

function Deliveries() { const [status, setStatus] = useState<NotificationStatus | "">(""); const [page, setPage] = useState(1); const query = useNotifications(status, page); return <section className="stack"><label>Status<select value={status} onChange={(event) => { setStatus(event.target.value as NotificationStatus | ""); setPage(1); }}><option value="">All</option>{["PENDING", "PROCESSING", "SENT", "FAILED", "DEAD_LETTER", "CANCELLED"].map((value) => <option key={value}>{value}</option>)}</select></label><div className="panel"><table className="table"><thead><tr><th>Type</th><th>Recipient</th><th>Status</th><th>Created</th><th>Sent</th><th>Attempts</th></tr></thead><tbody>{query.data?.items.map((item) => <tr key={item.id}><td><Link href={`/notifications/${item.id}`}>{LABELS[item.type] ?? item.type}</Link></td><td>{item.recipient}</td><td>{item.status}</td><td>{new Date(item.createdAt).toLocaleString()}</td><td>{item.delivery?.sentAt ? new Date(item.delivery.sentAt).toLocaleString() : "—"}</td><td>{item.delivery?.attempts ?? 0}</td></tr>)}</tbody></table></div><div><button disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button> <span> Page {page} </span><button disabled={!query.data || page * query.data.pageSize >= query.data.total} onClick={() => setPage(page + 1)}>Next</button></div></section>; }

