import { BadRequestException, ConflictException, Injectable, NotFoundException } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { PrismaService } from "../prisma/prisma.service";
import { CreateNotificationRuleDto, ListNotificationsDto, NOTIFICATION_EVENTS, UpdateNotificationRuleDto } from "./dto/notification.dto";

const TEMPLATES: Record<string, string> = { APPROVAL_REQUESTED: "approval.requested", APPROVAL_APPROVED: "approval.approved", APPROVAL_REJECTED: "approval.rejected", APPROVAL_EXPIRED: "approval.expired", EXECUTION_COMPLETED: "workflow.completed", EXECUTION_FAILED: "workflow.failed", EVENT_TRIGGER_FAILED: "event-trigger.failed", EVENT_CHAIN_DEPTH_EXCEEDED: "event-chain.depth-exceeded" };
const ROLES = new Set(["owner", "admin", "editor", "viewer"]);

@Injectable()
export class NotificationsService {
  constructor(private readonly prisma: PrismaService) {}
  listRules(organizationId: string) { return this.prisma.notificationRule.findMany({ where: { organizationId, deletedAt: null }, orderBy: { createdAt: "desc" }, select: { id: true, eventType: true, channel: true, enabled: true, connectionId: true, recipientConfigJson: true, filtersJson: true, templateKey: true, createdAt: true, updatedAt: true, connection: { select: { id: true, name: true, status: true } } } }); }
  async createRule(organizationId: string, userId: string, dto: CreateNotificationRuleDto) {
    const normalized = await this.validateRule(organizationId, dto);
    return this.prisma.$transaction(async (tx) => {
      const row = await tx.notificationRule.create({ data: { organizationId, eventType: dto.eventType, channel: "EMAIL", connectionId: dto.connectionId, enabled: dto.enabled, templateKey: dto.templateKey, recipientConfigJson: json(normalized.recipients), filtersJson: json(normalized.filters) } });
      await audit(tx, organizationId, userId, "notification_rule.created", row.id, { eventType: row.eventType, channel: row.channel }); return row;
    });
  }
  async updateRule(organizationId: string, userId: string, id: string, dto: UpdateNotificationRuleDto) {
    const current = await this.prisma.notificationRule.findFirst({ where: { id, organizationId, deletedAt: null } }); if (!current) throw new NotFoundException("Notification rule not found");
    const merged = { eventType: dto.eventType ?? current.eventType, channel: "EMAIL" as const, connectionId: dto.connectionId ?? current.connectionId, recipientConfig: dto.recipientConfig ?? record(current.recipientConfigJson), filters: dto.filters ?? record(current.filtersJson), templateKey: dto.templateKey ?? current.templateKey, enabled: dto.enabled ?? current.enabled } as CreateNotificationRuleDto;
    const normalized = await this.validateRule(organizationId, merged);
    return this.prisma.$transaction(async (tx) => { const row = await tx.notificationRule.update({ where: { id }, data: { eventType: merged.eventType, connectionId: merged.connectionId, recipientConfigJson: json(normalized.recipients), filtersJson: json(normalized.filters), templateKey: merged.templateKey, enabled: merged.enabled } }); await audit(tx, organizationId, userId, "notification_rule.updated", id, { eventType: row.eventType, channel: row.channel }); return row; });
  }
  async deleteRule(organizationId: string, userId: string, id: string) { const found = await this.prisma.notificationRule.findFirst({ where: { id, organizationId, deletedAt: null } }); if (!found) throw new NotFoundException("Notification rule not found"); return this.prisma.$transaction(async (tx) => { await tx.notificationRule.update({ where: { id }, data: { enabled: false, deletedAt: new Date() } }); await audit(tx, organizationId, userId, "notification_rule.deleted", id, { eventType: found.eventType, channel: found.channel }); return { deleted: true }; }); }
  async list(organizationId: string, query: ListNotificationsDto) { const where: Prisma.NotificationRequestWhereInput = { organizationId, ...(query.status ? { status: query.status as any } : {}), ...(query.type ? { type: query.type } : {}) }; const [items, total] = await this.prisma.$transaction([this.prisma.notificationRequest.findMany({ where, orderBy: { createdAt: "desc" }, skip: (query.page - 1) * query.pageSize, take: query.pageSize, include: { delivery: true, rule: { select: { id: true } } } }), this.prisma.notificationRequest.count({ where })]); return { items: items.map(publicNotification), page: query.page, pageSize: query.pageSize, total }; }
  async detail(organizationId: string, id: string) { const row = await this.prisma.notificationRequest.findFirst({ where: { id, organizationId }, include: { delivery: true, rule: { select: { id: true, eventType: true, connection: { select: { id: true, name: true } } } } } }); if (!row) throw new NotFoundException("Notification not found"); return publicNotification(row); }
  async retry(organizationId: string, userId: string, id: string) { const row = await this.prisma.notificationRequest.findFirst({ where: { id, organizationId }, include: { delivery: true } }); if (!row) throw new NotFoundException("Notification not found"); if (!row.delivery || !["FAILED", "DEAD_LETTER"].includes(row.status)) throw new ConflictException("Notification cannot be retried"); await this.prisma.$transaction(async (tx) => { await tx.notificationRequest.update({ where: { id }, data: { status: "PENDING", scheduledAt: new Date(), nextAttemptAt: null, lockedBy: null, lockedUntil: null } }); await tx.notificationDelivery.update({ where: { notificationRequestId: id }, data: { status: "PENDING", attempts: 0, failedAt: null, errorCategory: null, errorMessageSafe: null } }); await audit(tx, organizationId, userId, "notification.retried", id, { channel: row.channel, type: row.type, outcome: "pending" }, "NotificationRequest"); }); return this.detail(organizationId, id); }

  private async validateRule(organizationId: string, dto: CreateNotificationRuleDto) {
    if (!NOTIFICATION_EVENTS.includes(dto.eventType as any) || TEMPLATES[dto.eventType] !== dto.templateKey) throw new BadRequestException("Template is not compatible with event type");
    const connection = await this.prisma.connection.findFirst({ where: { id: dto.connectionId, organizationId, type: "smtp", status: "ACTIVE", deletedAt: null } }); if (!connection) throw new BadRequestException("Active SMTP connection not found");
    const recipients = validateRecipients(dto.eventType, dto.recipientConfig); const filters = validateFilters(dto.eventType, dto.filters); return { recipients, filters };
  }
}
function validateRecipients(eventType: string, value: unknown) { const input = record(value); if (input.kind === "EMAILS") { const emails = [...new Set((Array.isArray(input.emails) ? input.emails : []).map((v) => String(v).trim().toLowerCase()))]; if (!emails.length || emails.length > 50 || emails.some((email) => email.length > 254 || !/^[^\s@\r\n]+@[^\s@\r\n]+\.[^\s@\r\n]+$/.test(email))) throw new BadRequestException("Invalid recipient emails"); return { kind: "EMAILS", emails }; } if (input.kind === "APPROVAL_ROLES" && eventType.startsWith("APPROVAL_")) { const roles = [...new Set((Array.isArray(input.roles) ? input.roles : []).map(String))]; if (!roles.length || roles.some((role) => !ROLES.has(role))) throw new BadRequestException("Invalid approval recipient roles"); return { kind: "APPROVAL_ROLES", roles }; } throw new BadRequestException("Invalid recipient configuration"); }
function validateFilters(eventType: string, value: unknown) { const input = record(value); const allowed = eventType.startsWith("EXECUTION_") ? new Set(["workflowId", "status", "origin"]) : eventType.startsWith("APPROVAL_") ? new Set(["workflowId", "status"]) : new Set(); for (const [key, val] of Object.entries(input)) { if (!allowed.has(key) || typeof val !== "string" || !val || val.length > 128) throw new BadRequestException(`Invalid notification filter ${key}`); } return input; }
function publicNotification(row: any) { return { id: row.id, type: row.type, channel: row.channel, status: row.status, recipient: maskEmail(row.recipient), subject: row.subject, templateKey: row.templateKey, scheduledAt: row.scheduledAt, createdAt: row.createdAt, updatedAt: row.updatedAt, correlationId: row.correlationId, rule: row.rule, delivery: row.delivery ? { provider: row.delivery.provider, status: row.delivery.status, attempts: row.delivery.attempts, lastAttemptAt: row.delivery.lastAttemptAt, sentAt: row.delivery.sentAt, failedAt: row.delivery.failedAt, errorCategory: row.delivery.errorCategory, errorMessageSafe: row.delivery.errorMessageSafe } : null }; }
function maskEmail(value: string) { const [local, domain] = value.split("@"); return `${local.slice(0, 2)}***@${domain}`; }
function record(value: unknown): Record<string, any> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, any> : {}; }
function json(value: unknown): Prisma.InputJsonValue { return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue; }
function audit(tx: Prisma.TransactionClient, organizationId: string, actorUserId: string, action: string, resourceId: string, metadata: Record<string, unknown>, resourceType = "NotificationRule") { return tx.auditLog.create({ data: { organizationId, actorUserId, action, resourceType, resourceId, metadataJson: json(metadata) } }); }
