import { BadRequestException, ConflictException, NotFoundException } from "@nestjs/common";
import { NotificationsService } from "./notifications.service";

describe("NotificationsService", () => {
  it("scopes delivery detail to the organization", async () => { const prisma: any = { notificationRequest: { findFirst: jest.fn(async () => null) } }; await expect(new NotificationsService(prisma).detail("org-a", "request-b")).rejects.toBeInstanceOf(NotFoundException); expect(prisma.notificationRequest.findFirst).toHaveBeenCalledWith(expect.objectContaining({ where: { id: "request-b", organizationId: "org-a" } })); });
  it("does not retry sent deliveries", async () => { const prisma: any = { notificationRequest: { findFirst: jest.fn(async () => ({ id: "n", status: "SENT", delivery: {}, channel: "EMAIL", type: "EXECUTION_COMPLETED" })) } }; await expect(new NotificationsService(prisma).retry("org", "user", "n")).rejects.toBeInstanceOf(ConflictException); });
  it("validates SMTP tenancy and typed template when creating", async () => { const tx: any = { notificationRule: { create: jest.fn(async ({ data }) => ({ id: "rule", ...data })) }, auditLog: { create: jest.fn() } }; const prisma: any = { connection: { findFirst: jest.fn(async () => ({ id: "smtp" })) }, $transaction: jest.fn(async (callback) => callback(tx)) }; const result = await new NotificationsService(prisma).createRule("org", "user", { eventType: "EXECUTION_FAILED", channel: "EMAIL", connectionId: "smtp", recipientConfig: { kind: "EMAILS", emails: ["OPS@example.com"] }, filters: { workflowId: "workflow" }, templateKey: "workflow.failed", enabled: true }); expect(result.recipientConfigJson).toEqual({ kind: "EMAILS", emails: ["ops@example.com"] }); expect(prisma.connection.findFirst).toHaveBeenCalledWith({ where: expect.objectContaining({ organizationId: "org", type: "smtp" }) }); });
  it("rejects arbitrary templates, filters and cross-tenant SMTP connections", async () => { const missingConnection: any = { connection: { findFirst: jest.fn(async () => null) } }; const service = new NotificationsService(missingConnection); await expect(service.createRule("org-a", "user", { eventType: "EXECUTION_FAILED", channel: "EMAIL", connectionId: "org-b-smtp", recipientConfig: { kind: "EMAILS", emails: ["ops@example.com"] }, filters: {}, templateKey: "workflow.failed", enabled: true })).rejects.toBeInstanceOf(BadRequestException); await expect(service.createRule("org-a", "user", { eventType: "EXECUTION_FAILED", channel: "EMAIL", connectionId: "smtp", recipientConfig: { kind: "EMAILS", emails: ["ops@example.com"] }, filters: {}, templateKey: "user.html", enabled: true })).rejects.toBeInstanceOf(BadRequestException); });
  it("returns only safe delivery fields and applies tenant/status pagination", async () => { const raw = { id: "n", type: "EXECUTION_FAILED", channel: "EMAIL", status: "FAILED", recipient: "operator@example.com", subject: "Failed", templateKey: "workflow.failed", scheduledAt: new Date(), createdAt: new Date(), updatedAt: new Date(), correlationId: "c", payloadJson: { secret: "hidden" }, rule: { id: "r" }, delivery: { provider: "smtp", status: "FAILED", attempts: 2, lastAttemptAt: new Date(), sentAt: null, failedAt: new Date(), errorCategory: "TRANSIENT", errorMessageSafe: "Temporary failure", providerMessageId: "private" } }; const prisma: any = { notificationRequest: { findMany: jest.fn(async () => [raw]), count: jest.fn(async () => 1) }, $transaction: jest.fn(async (operations) => Promise.all(operations)) }; const result = await new NotificationsService(prisma).list("org-a", { status: "FAILED", page: 2, pageSize: 10 }); expect(prisma.notificationRequest.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: { organizationId: "org-a", status: "FAILED" }, skip: 10, take: 10 })); expect(result.items[0].recipient).toBe("op***@example.com"); expect(result.items[0]).not.toHaveProperty("payloadJson"); expect(result.items[0].delivery).not.toHaveProperty("providerMessageId"); });
  it("does not update or delete a cross-tenant rule", async () => { const prisma: any = { notificationRule: { findFirst: jest.fn(async () => null) } }; const service = new NotificationsService(prisma); await expect(service.updateRule("org-b", "user", "rule-a", {})).rejects.toBeInstanceOf(NotFoundException); await expect(service.deleteRule("org-b", "user", "rule-a")).rejects.toBeInstanceOf(NotFoundException); });
});
