"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useState } from "react";
import { ConfirmDialog } from "../../../components/confirm-dialog";
import { ErrorMessage } from "../../../components/error-message";
import { RequireAuth } from "../../../features/auth/require-auth";
import { useAuth } from "../../../features/auth/use-auth";
import { useApproval, useDecideApproval } from "../../../features/approvals/hooks";
export default function ApprovalDetailPage() { const id = String(useParams().approvalId); const query = useApproval(id); const decide = useDecideApproval(id); const [comment, setComment] = useState(""); const [pendingDecision, setPendingDecision] = useState<"approve"|"reject"|null>(null); const { organizations, activeOrganizationId } = useAuth(); const role = organizations.find((item) => item.id === activeOrganizationId)?.role; const canDecide = role === "owner" || role === "admin" || (role === "editor" && query.data?.allowedRoles.includes("editor")); const submit = () => { if (!pendingDecision) return; decide.mutate({ decision: pendingDecision, comment }, { onSettled: () => setPendingDecision(null) }); }; return <RequireAuth><main className="content stack"><Link href="/approvals">← Approvals</Link>{query.error && <ErrorMessage error={query.error} onRetry={() => query.refetch()} />}{query.data && <><h1>{query.data.title}</h1><section className="panel stack"><p>{query.data.description}</p>{query.data.summary && <pre>{query.data.summary}</pre>}<dl><dt>Status</dt><dd>{query.data.status}</dd><dt>Workflow</dt><dd>{query.data.workflow.name}</dd><dt>Execution</dt><dd><Link href={`/executions/${query.data.executionId}`}>{query.data.executionId}</Link></dd><dt>Requested</dt><dd>{new Date(query.data.requestedAt).toLocaleString()}</dd><dt>Expires</dt><dd>{query.data.expiresAt ? new Date(query.data.expiresAt).toLocaleString() : "Never"}</dd></dl>{query.data.status === "PENDING" && canDecide && <><label>Optional comment<textarea maxLength={1000} value={comment} onChange={(event) => setComment(event.target.value)} /></label><div><button disabled={decide.isPending} onClick={() => setPendingDecision("approve")}>Approve</button> <button disabled={decide.isPending} onClick={() => setPendingDecision("reject")}>Reject</button></div></>}</section><ConfirmDialog open={Boolean(pendingDecision)} title={`${pendingDecision === "approve" ? "Approve" : "Reject"} request?`} description="This decision is final and will resume the workflow." confirmLabel={pendingDecision === "approve" ? "Approve" : "Reject"} onConfirm={submit} onCancel={() => setPendingDecision(null)} />{decide.error && <ErrorMessage error={decide.error} />}</>}</main></RequireAuth>; }
