"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiClient } from "../../lib/api-client";
import type { DependencyMapping, TemplateList, TemplatePreview, TemplateVersion, WorkflowTemplate } from "./types";

export function useTemplates(status = "") { return useQuery({ queryKey: ["templates", status], queryFn: () => apiClient.get<TemplateList>("/workflow-templates", { status }) }); }
export function useTemplate(id: string) { return useQuery({ queryKey: ["templates", id], queryFn: () => apiClient.get<WorkflowTemplate>(`/workflow-templates/${id}`), enabled: Boolean(id) }); }
export function useTemplateVersions(id: string) { return useQuery({ queryKey: ["templates", id, "versions"], queryFn: () => apiClient.get<TemplateVersion[]>(`/workflow-templates/${id}/versions`), enabled: Boolean(id) }); }
export function useTemplateVersion(templateId: string, versionId?: string) { return useQuery({ queryKey: ["templates", templateId, "versions", versionId], queryFn: () => apiClient.get<TemplateVersion>(`/workflow-templates/${templateId}/versions/${versionId}`), enabled: Boolean(templateId && versionId) }); }
export function useCreateTemplate() { const client = useQueryClient(); return useMutation({ mutationFn: (dto: { name: string; description?: string; workflowId: string; workflowVersionId: string }) => apiClient.post<WorkflowTemplate>("/workflow-templates/from-workflow-version", dto), onSuccess: () => client.invalidateQueries({ queryKey: ["templates"] }) }); }
export function usePublishTemplate(templateId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (versionId: string) => apiClient.patch(`/workflow-templates/${templateId}/versions/${versionId}/publish`, {}), onSuccess: () => client.invalidateQueries({ queryKey: ["templates", templateId] }) }); }
export function useArchiveTemplate(templateId: string) { const client = useQueryClient(); return useMutation({ mutationFn: () => apiClient.patch(`/workflow-templates/${templateId}/archive`, {}), onSuccess: () => client.invalidateQueries({ queryKey: ["templates"] }) }); }
export function useTemplatePreview(templateId: string, versionId?: string) { return useMutation({ mutationFn: (mappings: DependencyMapping[]) => apiClient.post<TemplatePreview>(`/workflow-templates/${templateId}/versions/${versionId}/preview`, { mappings }) }); }
export function useInstantiateTemplate(templateId: string, versionId?: string) { const client = useQueryClient(); return useMutation({ mutationFn: (dto: { name: string; description?: string; mappings: DependencyMapping[] }) => apiClient.post<any>(`/workflow-templates/${templateId}/versions/${versionId}/instantiate`, dto), onSuccess: () => client.invalidateQueries({ queryKey: ["workflows"] }) }); }
export function useCloneWorkflow(workflowId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (dto: { sourceWorkflowVersionId: string; name: string; description?: string; mappings: DependencyMapping[] }) => apiClient.post<any>(`/workflows/${workflowId}/clone`, dto), onSuccess: () => client.invalidateQueries({ queryKey: ["workflows"] }) }); }
export function useCloneWorkflowPreview(workflowId: string) { return useMutation({ mutationFn: (dto: { sourceWorkflowVersionId: string; name: string; description?: string; mappings: DependencyMapping[] }) => apiClient.post<TemplatePreview>(`/workflows/${workflowId}/clone-preview`, dto) }); }
