import { matchesNotificationFilters, notificationIdempotency, safePayload, validEmail } from "./notification-domain";
import { NotificationTemplates } from "./notification-templates";

const event: any = { id: "event-1", type: "APPROVAL_REQUESTED", organizationId: "org-1", subject: { type: "approval", id: "approval-1" }, data: { approvalId: "approval-1", workflowId: "workflow-1", title: "<script>alert(1)</script> Review", description: "<img src=x onerror=alert(1)>" } };
describe("notification domain", () => {
  it("uses the business subject and normalized recipient for stable idempotency", () => { expect(notificationIdempotency("rule-1", event, "OPS@Example.com")).toBe(notificationIdempotency("rule-1", { ...event, id: "duplicate-event" }, "ops@example.com")); });
  it("validates recipients and filters", () => { expect(validEmail("ops@example.com")).toBe(true); expect(validEmail("victim@example.com\r\nBcc:x@example.com")).toBe(false); expect(matchesNotificationFilters(event, { workflowId: "workflow-1" })).toBe(true); expect(matchesNotificationFilters(event, { workflowId: "other" })).toBe(false); });
  it("projects safe bounded payloads", () => { const result = safePayload(event); expect(result).not.toHaveProperty("authorization"); expect(result.title).toContain("script"); });
  it("escapes controlled HTML and creates text fallback", () => { const rendered = new NotificationTemplates().render("approval.requested", { title: "<script>x</script>", description: "<b>safe</b>", link: "http://localhost:3000/approvals/approval-1" }); expect(rendered.html).not.toContain("<script>"); expect(rendered.html).not.toContain("<b>"); expect(rendered.text).toContain("Open in FlowMind"); });
  it("rejects unknown templates and external links", () => { expect(() => new NotificationTemplates().render("unknown", {})).toThrow("Unknown notification template"); const rendered = new NotificationTemplates().render("workflow.failed", { link: "https://evil.example/executions/1" }); expect(rendered.html).not.toContain("evil.example"); });
  it.each([["approval.requested", "Approval requested"], ["approval.approved", "Approval approved"], ["workflow.failed", "Workflow failed"], ["workflow.completed", "Workflow completed"]])("renders controlled %s template", (key, label) => { const rendered = new NotificationTemplates().render(key, { title: "Example", status: "COMPLETED" }); expect(rendered.subject).toContain(label); expect(rendered.text).toContain(label); expect(rendered.html).toContain(label); });
  it("bounds missing and malicious values", () => { const rendered = new NotificationTemplates().render("workflow.failed", { title: `bad\r\nBcc: victim@example.com${"x".repeat(1_000)}`, description: `<script>${"y".repeat(5_000)}</script>` }); expect(rendered.subject.length).toBeLessThanOrEqual(300); expect(rendered.subject).not.toMatch(/[\r\n]/); expect(rendered.text.length).toBeLessThan(3_000); expect(rendered.html).not.toContain("<script>"); expect(new NotificationTemplates().render("approval.requested", {}).subject).toContain("FlowMind notification"); });
});
