import { ValidationPipe, type INestApplication } from "@nestjs/common";
import { Test } from "@nestjs/testing";
import { JwtService } from "@nestjs/jwt";
import { PrismaClient } from "@prisma/client";
import request from "supertest";
import { AppModule } from "../src/app.module";

const prisma = new PrismaClient(); const prefix = `notifications-api-${Date.now()}`;
describe("notifications API", () => { let app: INestApplication; beforeAll(async () => { process.env.DATABASE_URL ??= "postgresql://postgres:postgres@localhost:5432/automation_platform"; process.env.REDIS_URL ??= "redis://localhost:6379"; process.env.JWT_ACCESS_SECRET = "notification-access-secret"; process.env.JWT_REFRESH_SECRET = "notification-refresh-secret"; const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile(); app = moduleRef.createNestApplication(); app.useGlobalPipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true, transform: true })); await app.init(); }, 30_000); afterEach(clean); afterAll(async () => { await clean(); await app.close(); await prisma.$disconnect(); });
  it("enforces rule RBAC, tenant-scoped CRUD and typed inputs", async () => { const fixture = await tenant("rules"); await request(app.getHttpServer()).get("/notification-rules").set(headers(fixture.viewer, fixture.organizationId)).expect(200); await request(app.getHttpServer()).post("/notification-rules").set(headers(fixture.viewer, fixture.organizationId)).send(ruleDto(fixture.connectionId)).expect(403); const created = await request(app.getHttpServer()).post("/notification-rules").set(headers(fixture.editor, fixture.organizationId)).send(ruleDto(fixture.connectionId)).expect(201); await request(app.getHttpServer()).patch(`/notification-rules/${created.body.id}`).set(headers(fixture.editor, fixture.organizationId)).send({ enabled: false }).expect(200); const other = await tenant("other"); await request(app.getHttpServer()).patch(`/notification-rules/${created.body.id}`).set(headers(other.editor, other.organizationId)).send({ enabled: true }).expect(404); await request(app.getHttpServer()).post("/notification-rules").set(headers(fixture.editor, fixture.organizationId)).send({ ...ruleDto(fixture.connectionId), templateKey: "arbitrary.html" }).expect(400); await request(app.getHttpServer()).delete(`/notification-rules/${created.body.id}`).set(headers(fixture.editor, fixture.organizationId)).expect(200); expect(await prisma.auditLog.count({ where: { organizationId: fixture.organizationId, action: { in: ["notification_rule.created", "notification_rule.updated", "notification_rule.deleted"] } } })).toBe(3); });
  it("lists safe paginated deliveries, hides cross-tenant IDs and restricts retry to admin", async () => { const fixture = await tenant("deliveries"); const rule = await prisma.notificationRule.create({ data: { organizationId: fixture.organizationId, eventType: "EXECUTION_FAILED", connectionId: fixture.connectionId, recipientConfigJson: { kind: "EMAILS", emails: ["operator@example.com"] }, filtersJson: {}, templateKey: "workflow.failed" } }); const row = await prisma.notificationRequest.create({ data: { organizationId: fixture.organizationId, notificationRuleId: rule.id, sourceEventId: "event", type: "EXECUTION_FAILED", recipient: "operator@example.com", subject: "Workflow failed", templateKey: "workflow.failed", payloadJson: { secret: "must-not-return" }, idempotencyKey: "key", status: "DEAD_LETTER" } }); await prisma.notificationDelivery.create({ data: { organizationId: fixture.organizationId, notificationRequestId: row.id, status: "DEAD_LETTER", attempts: 5, failedAt: new Date(), errorCategory: "TRANSIENT", errorMessageSafe: "Temporary SMTP delivery failure", providerMessageId: "private-provider-id" } }); const list = await request(app.getHttpServer()).get("/notifications?status=DEAD_LETTER&page=1&pageSize=10").set(headers(fixture.viewer, fixture.organizationId)).expect(200); expect(list.body.total).toBe(1); expect(list.body.items[0].recipient).toBe("op***@example.com"); expect(JSON.stringify(list.body)).not.toMatch(/must-not-return|private-provider-id|payloadJson/i); const other = await tenant("outsider"); await request(app.getHttpServer()).get(`/notifications/${row.id}`).set(headers(other.viewer, other.organizationId)).expect(404); await request(app.getHttpServer()).post(`/notifications/${row.id}/retry`).set(headers(fixture.editor, fixture.organizationId)).expect(403); await request(app.getHttpServer()).post(`/notifications/${row.id}/retry`).set(headers(fixture.admin, fixture.organizationId)).expect(201); expect(await prisma.notificationRequest.findUnique({ where: { id: row.id } })).toMatchObject({ status: "PENDING" }); expect(await prisma.auditLog.count({ where: { organizationId: fixture.organizationId, action: "notification.retried", resourceId: row.id } })).toBe(1); await request(app.getHttpServer()).post(`/notifications/${row.id}/retry`).set(headers(fixture.admin, fixture.organizationId)).expect(409); });
});
function ruleDto(connectionId: string) { return { eventType: "EXECUTION_FAILED", channel: "EMAIL", connectionId, recipientConfig: { kind: "EMAILS", emails: ["ops@example.com"] }, filters: { status: "FAILED" }, templateKey: "workflow.failed", enabled: true }; }
async function tenant(name: string) { const organization = await prisma.organization.create({ data: { name, slug: `${prefix}-${name}-${Math.random().toString(16).slice(2)}` } }); const owner = await member(organization.id, "owner", `${name}-owner`); const admin = await member(organization.id, "admin", `${name}-admin`); const editor = await member(organization.id, "editor", `${name}-editor`); const viewer = await member(organization.id, "viewer", `${name}-viewer`); const connection = await prisma.connection.create({ data: { organizationId: organization.id, name: "SMTP", type: "smtp", status: "ACTIVE", configJson: {}, createdByUserId: owner.userId } }); return { organizationId: organization.id, connectionId: connection.id, owner, admin, editor, viewer }; }
async function member(organizationId: string, role: "owner" | "admin" | "editor" | "viewer", name: string) { const user = await prisma.user.create({ data: { email: `${prefix}-${name}-${Math.random()}@example.com`, name, passwordHash: "hash" } }); await prisma.organizationMember.create({ data: { organizationId, userId: user.id, role } }); return { userId: user.id, token: await new JwtService().signAsync({ sub: user.id, email: user.email, tokenType: "access", jti: user.id }, { secret: process.env.JWT_ACCESS_SECRET }) }; }
function headers(user: { token: string }, organizationId: string) { return { authorization: `Bearer ${user.token}`, "x-organization-id": organizationId }; }
async function clean() { const organizations = await prisma.organization.findMany({ where: { slug: { startsWith: prefix } }, select: { id: true } }); await prisma.organization.deleteMany({ where: { id: { in: organizations.map((row) => row.id) } } }); await prisma.user.deleteMany({ where: { email: { startsWith: prefix } } }); }
